apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-2022-06-01t21-13-33
spec:
  encryptedData:
    .dockerconfigjson: AgAIO5RtyF78v6txBmQq5qo1FkJ3MUm+ykj9eZNjSaiwgRY8dR8gXf6C/A9HY2g5ImWEQOCRpwsxTHflrLbC3vURjUVdYCGFJ7dC8GN5FkUURqQ0vNFPje1ryx1Mb983A6mKP9QzGI+fWdhYVrcRzs8i8whmTmxUDJoa/TgeIOTVNovBFdzHk+eaV5XzLE/LwZD4GWH1EnCYH19OpyW/8DinfusVcX0S7JTRkG8Iv3/+Fpjk9YjzLDLc93ixJ+Cah7bgL6An7IXMEaILER+FX35Zuxl9WOhDlZ2WSkkVU4ub6HgHCi92EdDCXO2XRN+KuRtiNU5aOJM3nGFKGrQXQFF2cfgR3Xp7GiBeivFzQv/3uKekq0N0seA0Hbg4/0bYT48hk8L2eZhTvMfGf3f+LdGbWc+83njgZItlXpi2eXxWTxQWfp2GAWtnTe4A0Ypnb/+Ix4n0McQa8nRALwkZbntPagvZXVaBucG87wYZjT5H7I0VdsLvs0DcLy0zKhcVZ0y+5E+9iUO+pDDyImqsXF0gRVjl3WrwLSFWkcmSguBSMENBUhploAgtxwWn7J3bc1q96rdFA7giC/m/9/PGZfFoZYqKRF4hM6bM3kvtczPJeaThRCDbZnT2HkNrra2lZomuOWWbTDTKh6TSQkhuhkk/Zg8Id+6WS4Nl8VuG+0RBZcJvnETakRk+6uE+rS+KWtTtkGDo4NqIiA1jr3Ewxtq4Ilke1zAK7emvCKpUTo6vVy8kE+EwRTIOacTeT/QLljwTKTL6DxIr5/KODf71HwFPOsQfPaLipaIgkQ2hz/QnnslN5Y9jxTHRngJ7UvljegHWjLZUv1tCUikAiK3HFLQC2aR+/fPegyNVcZE3iiSIJVl8ndA/uXm+z3yu2xHHEbDCKvHEFC/ZvlUGq4tTCd/nB0RGG67shVC+FP/doXj79ua7NzOwmn+zLd+JaOZOkbA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-2022-06-01t21-13-33
    type: kubernetes.io/dockerconfigjson

